name: Run Playwright Tests (Non Scheduled)

on:
  workflow_dispatch:
    inputs:
      test_file:
        description: "Spec file yang mau dijalankan"
        required: false
        default: ""

      keyword:
        description: "Keyword test title (Playwright --grep)"
        required: false
        default: ""

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependecies
        run: npm ci

      - name: Install Playwright Browser
        run: npx playwright install --with-deps chromium

      - name: Set Timezone to WIB
        run: sudo timedatectl set-timezone Asia/Jakarta

      - name: Run tests
        id: run_tests
        run: |
          mkdir -p reports
          
          CMD="npx playwright test"

          if [ -n "${{ github.event.inputs.test_file }}" ]; then
            CMD="$CMD ./tests/${{ github.event.inputs.test_file }}"
          else
            CMD="$CMD ./tests/reservasi_test.spec.js"
          fi

          if [ -n "${{ github.event.inputs.keyword }}" ]; then
            CMD="$CMD --grep '${{ github.event.inputs.keyword }}'"
          fi

          CMD="$CMD --reporter=json --project=chromium"

          echo "Running: $CMD"
          eval "$CMD" > reports/result.json || true
          
        continue-on-error: true

      - name: Build Telegram Report
        run: |
          node <<'EOF'
          const fs = require('fs');

          function formatDuration(ms) {
            const totalSeconds = Math.floor(ms / 1000);
            const hours = Math.floor(totalSeconds / 3600);
            const minutes = Math.floor((totalSeconds % 3600) / 60);
            const seconds = totalSeconds % 60;

            return [
              String(hours).padStart(2, '0'),
              String(minutes).padStart(2, '0'),
              String(seconds).padStart(2, '0'),
            ].join(':');
          }

          const data = JSON.parse(fs.readFileSync('reports/result.json', 'utf8'));
          const suites = data.suites || [];
          const stats = data.stats || {};

          const executionTime = stats.startTime ? new Date(stats.startTime) : new Date();
          const duration = stats.duration || 0;
          const durationFormatted = formatDuration(duration);

          const date = executionTime.toLocaleDateString('id-ID');
          const time = executionTime.toLocaleTimeString('id-ID', { hour12: false });

          let total = 0;
          let passed = 0;
          let failed = 0;
          let flaky = 0;
          let detail = '';
          let failedDetail = '';

          suites.forEach(suite => {
            if (!suite.file) return;

            (suite.specs || []).forEach(spec => {
              const test = spec.tests?.[0];
              const results = test?.results || [];

              const hasPassed = results.some(r => r.status === 'passed');
              const hasFailed = results.some(r => r.status !== 'passed');
              
              let status = results.at(-1)?.status || 'unknown';

              if (results.length > 1 && hasPassed && hasFailed) {
                status = 'flaky';
              }

              total++;
              
              if (status === 'passed') {
                passed++;
              } else if (status === 'flaky') {
                flaky++;
              } else {
                failed++;

                const lastResult = results.at(-1);

                const rawError =
                  lastResult?.error?.message ||
                  lastResult?.error ||
                  lastResult?.errors?.[0]?.message ||
                  'No error message available';

                const errorMessage = String(rawError)
                  .replace(/\x1B\[[0-9;]*m/g, '')
                  .replace(/\n\s*\n+/g, '\n')
                  .trim();

                const shortError = errorMessage
                  .split('\n')
                  .slice(0, 5)
                  .join('\n');
                  
                failedDetail +=
                  `❌ ${spec.title}\n` +
                  `💥 ${shortError}\n\n`;
              }

            });

          });

          const report =
            `AUTOMATE TEST REPORT

             📅 Date: ${date} 
             🕒 Time: ${time}
              ⏱ Duration: ${durationFormatted}

             Summary
             🧪 Total: ${total}
             ✅ Passed: ${passed}
             ⚠️ Flaky: ${flaky}
             ❌ Failed: ${failed}

             Failed Detail
             ${failedDetail || 'None'}
             `;

          fs.appendFileSync(
            process.env.GITHUB_ENV,
            `TELEGRAM_REPORT<<EOF\n${report}\nEOF\n`
          );
          EOF

      - name: Send Telegram Notification
        if: always()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID_NON_SCHEDULED }} \
            --data-urlencode "text=$TELEGRAM_REPORT"

      - name: Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            test-results
            playwright-report
